<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>K3SManager.Kubernetes</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\K3SManager.Core\K3SManager.Core.csproj" />
  </ItemGroup>

</Project>
